### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Mxnet123** [ahogg/HRTF-upsampling-with-a-generative-adversarial-network-using-a-gnomonic-equiangular-projection#1]
Hello，when I run main.py preprocess --hpc False --tag ari-upscale-4, I find file_ext = re.findall(re.escape(input_dir) + '/(. *)_[0-9]*[a-z]*.pickle$', f)[0] with an error: IndexError: list index out of range

**Comment by ahogg** [comment]
There are likely differences in your file names compared to mine.
