### ISSUE TITLE
ModuleNotFoundError: No module named 'hrtfdata'

### ISSUE THREAD

**Issue by hu-junsheng** [ahogg/HRTF-upsampling-with-a-generative-adversarial-network-using-a-gnomonic-equiangular-projection#2]
Hi, I got this error: ModuleNotFoundError: No module named 'hrtfdata'

**Comment by PawelBaran2001** [comment]
I have the same problem. README does not specify what it is, is it an internal package of their organization or something? I tried to replace it with my own code to load sofa files, but it is not specified what structure the code later expects, so it is impossible.

**Comment by ahogg** [comment]
Sorry, I need to update the code for the new library. 

​The library 'hrtfdata' is now called 'hartufo', which can be found here: https://github.com/jpauwels/hartufo

The new library has been restructured, so you will likely get some errors with the class names, etc... 

If you would like, I am happy to share my latest code base with you... although it is messy...
