### ISSUE TITLE
ModuleNotFoundError: No module named 'hrtfdata'

### ISSUE THREAD

**Issue by pengbolyu** [ahogg/HRTF-upsampling-with-a-generative-adversarial-network-using-a-gnomonic-equiangular-projection#3]
Hello, I am interested in this project. However, some errors occurred during running. Which version of the 'hrtfdata' library is being used? Or could you share the latest code?

**Comment by ahogg** [comment]
I have just made my latest code available here: https://github.com/ahogg/Exploring-the-impact-of-transfer-learning-on-GAN-based-HRTF-upsampling/tree/single_node_upsampling 

This uses the more recent libraries. I hope this is helpful to you.
